version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "resume-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14yse7kf4qbaw"
s3_prefix = "resume-backend"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
